### ISSUE TITLE
Унифицировать название типов

### ISSUE THREAD

**Issue by FrediKats** [ronimizy/BaseComputer#1]
![image](https://user-images.githubusercontent.com/22368203/116746807-ba2cf900-aa05-11eb-9ca2-e14a2983c26b.png)

Int16 -> UInt16
Int32 -> UInt32

Обычно, когда байтики перекладывают, то явно указывают размер.

**Comment by ronimizy** [comment]
В папке "Extensions" лежат экстеншены к структурам, название файла - название структуры к которой экстеншен. 
Все унифицировано :)
